### PR TITLE
fix: tests

### PR DESCRIPTION
**Pull request by sjuergen**

### CODE REVIEW

**Comment by PTKu** [comment]
@sjuergen I see you needed to refactor the tests due to changes in method overload handling in v4. Is this the intended way of overload behavior? Should we refactor the existing code?

**Comment by sjuergen** [comment]
Hi @PTKu, 

this is a possible workaround for the overload issue. Another one is, to rename the Interface of the user defined assertions into e.g. Equal(a : <mytype>, e : <mytype>). 

Would this be an acceptable way? 

Nevertheless I'll try to get some information if there are other solutions possible. 

Regards

**Comment by sjuergen** [comment]
Hi @PTKu,
for enum it hasn't changed. For named values it has changed. 

Enums are more or less typeless while named values are bound on a type like INT, WORD and so on. That means, you can calculate with named values or assign a INT based named value to any other INT variable. Named values are not a new data type with a subset of INT value. They can take each value of the INT value range. 

That means: for all named values, you can use the system specific Assertions.

**Comment by PTKu** [comment]
Thanks for the clarification @sjuergen. It makes sense - in a way - with the named values. 
As for the IEC. On the one hand, I appreciate the fidelity and consistency with the standard; on the other, the new editions are released every decade or so, which is the pace at which it cannot reflect the needs of the industry. Besides that, too many actors with different interests are having a say in the IEC61131-3, which is not always beneficial and halts further development... And so, I think you should consider extending the ST regardless of what IEC says.

**Comment by sjuergen** [comment]
Hi @PTKu thanks for your feedback. 
 In the case of named values, I would say, the IEC fine... I'll give you an example:

```
    FUNCTION_BLOCK Foo
        
        VAR_OUTPUT
            ERROR_CODE : Errors;            
        END_VAR
                    
        ERROR_CODE := Errors#NO_ERROR;

        IF (true) THEN
            ERROR_CODE := SpecialErrorCodes#SUPER_ERROR OR WORD#16#8FFF;
        END_IF;
    END_FUNCTION_BLOCK

    TYPE
        Errors : WORD (NO_ERROR := WORD#16#0000);
        ErrorCode : WORD (GENERAL_ERROR := WORD#16#8001, CONFIG_ERROR := WORD#16#8002) := Errors#NO_ERROR;
        SpecialErrorCodes : WORD (SUPER_ERROR := WORD#16#8123, ANOTHER_SUPER_ERRROR := WORD#16#8299) := Errors#NO_ERROR;
    END_TYPE

```
In this example, it's fine when the named value is handled as an WORD. So you can assign different "named values" to each other as long they're of the same base type.

What do you think?

**Comment by PTKu** [comment]
I am OK with that. It opens some possibilities, but it may also introduce some inconsistencies. One must remember that he is working with named values and their nature.

**Pull request merged**
